---
output: html_document
title: "MARCviz package"
---

The `MARCviz` package contains the function `viz_MARC` for creating the Meta-Analytic Rain Cloud (MARC) Plot, from [Fitzgerald & Tipton (2022)](https://www.tandfonline.com/doi/abs/10.1080/19345747.2022.2031366). 

**Note, this package is still under construction!** 

To install the package, run the following code:

```{r, eval = FALSE}
devtools::install_github("kgfitzgerald/MARCviz")
```

Once installed, you can load the package and pull up the help documentation for the `viz_MARC` function. 

```{r}
library(MARCviz)
?viz_MARC
```

Produce MARC plot:

```{r, warning = FALSE, message = FALSE, eval = FALSE}
library(tidyverse)
#read in meta-analytic dataset
data(viz_MA_data)

#specify vector of effect sizes
d_j <- viz_MA_data %>% filter(k == 100) %>% pull(d_j)
#specify vector of standard errors
se_j <- viz_MA_data %>% filter(k == 100) %>% pull(se_j)

#create MARC plot (default is interactive plotly object)
viz_MARC(d_j, se_j)

#create static MARC plot (ggplot object)
viz_MARC(d_j, se_j, type = "static")
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
library(htmltools)
#read in meta-analytic dataset
data(viz_MA_data)

#specify vector of effect sizes
d_j <- viz_MA_data %>% filter(k == 100) %>% pull(d_j)
#specify vector of standard errors
se_j <- viz_MA_data %>% filter(k == 100) %>% pull(se_j)

viz_MARC(d_j, se_j)
```


